### ISSUE TITLE
Ipv6 addresses do not display properly

### ISSUE THREAD

**Issue by DO-Ui** [trakBan/ipfetch#15]
When trying to use ipfetch with an ipv6 address, it only shows the first 4 digits of the ip.
![image](https://user-images.githubusercontent.com/68296986/159381687-1e7a46b5-aafc-4ea8-ba2c-f2ffa5bb0db4.png)

**Comment by Costinteo** [comment]
This is due to the fact that I've parsed the IP Addresses with IPv4 in mind only. Should be an easy fix, I'll send a pull request with it later.

Thanks for reporting this!

**Comment by trakBan** [comment]
> 

I was just working on this as you typed this, it should be easy because you just need to remove the regex.
