### ISSUE TITLE
Error: "IP is invalid or API is down!"

### ISSUE THREAD

**Issue by Slipjack9600** [trakBan/ipfetch#24]
It appears the seeip.org/geoip API really is down, and has been down for quite a while.

**Comment by Costinteo** [comment]
Seems to me it still works properly? Is it up now, or?
For example, this url from the official API doc works:
https://ip.seeip.org/geoip/208.67.222.222

**Comment by trakBan** [comment]
seeip seeems to be very unstable, sometimes it works sometimes it doesn't. In the long run ipfetch should switch their API to someone else.
