### ISSUE TITLE
Don't write ip.json in current working director

### ISSUE THREAD

**Issue by ranile** [trakBan/ipfetch#3]
https://github.com/trakBan/ipfetch/blob/b62c7d88eda9a4e3d50638a2875de7efe968dcd7/ipfetch#L4

https://github.com/trakBan/ipfetch/blob/b62c7d88eda9a4e3d50638a2875de7efe968dcd7/ipfetch#L8

If there's a file called `ip.json` in the current working directory, it would be overwritten. It is better to use a variable to store the contents so nothing is writers permanently to file system. If a file must be used, consider writing to `/tmp/ip.json`

**Comment by trakBan** [comment]
I will add it in the next update
